import { jsPDF } from 'jspdf';

interface Document {
  id: string;
  type: string;
  title: string;
  content: string;
  createdAt: string;
}

export function generatePDF(document: Document): void {
  const pdf = new jsPDF();
  
  // Set up document properties
  pdf.setProperties({
    title: document.title,
    subject: `${document.type} document`,
    author: 'TysunMic',
    creator: 'TysunMic Legal Document Generator'
  });

  // Add header
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text(document.title, 20, 30);
  
  // Add generation date
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  const generateDate = new Date(document.createdAt).toLocaleDateString();
  pdf.text(`Generated on: ${generateDate}`, 20, 40);
  
  // Add powered by text
  pdf.text('Generated by TysunMic - Free Legal Documents', 20, 45);
  
  // Add content
  pdf.setFontSize(12);
  const splitContent = pdf.splitTextToSize(document.content, 170);
  pdf.text(splitContent, 20, 60);
  
  // Add footer
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.text(`Page ${i} of ${pageCount}`, 20, 280);
    pdf.text('This document was generated by TysunMic and is for informational purposes only.', 20, 285);
    pdf.text('Consult with a qualified attorney for legal advice. Support: Tserver@internetclock.com', 20, 290);
  }
  
  // Download the PDF
  pdf.save(`${document.title.replace(/\s+/g, '_')}.pdf`);
}
